### ISSUE TITLE
resolving gives @ 

### ISSUE THREAD

**Issue by jdutchak** [pubky/pkarr#35]
i am testing this and when i publish foo / bar and resolve it - how come i only see @ for name and nothing for value?

**Comment by Nuhvi** [comment]
Ah, I suppose you are publishing from the web app, I must have a bug in the frontend logic there, just too busy with the Rust implementation to hunt it down.


But this is the second complaint, so I will prioritize it. Thanks @jdutchak

**Comment by Nuhvi** [comment]
In the meantime, the CLI works well if you want to test Pkarr itself not the demo web app necessarily.

**Comment by jdutchak** [comment]
got it working on web - question 
if i add a record say 
foo / bar
then resolve it 
then add 
foo / baz

i noticed that upon resolving sometimes i get foo/bar and sometime i get foo/baz 
is this the expected behavior?

**Comment by Nuhvi** [comment]
Yes and no.

Yes because the relay is acting as a transparent relay, and it resolves optimistically (it returns the first result it sees) to be fast instead of thorough.

No because actual applications should be keeping cached versions of the records for long time, thus when they see an older version, they don't immediately return it to the user, and instead wait till they see a more recent version or exhaust the DHT traversal with no new versions, and then return the one they already saw.

So... expect the DHT to have multiple versions on different nodes, and don't expect strong consistency, design your app to tolerate that.

**Comment by jdutchak** [comment]
ty for the info
