### ISSUE TITLE
How is this different from IPFS?

### ISSUE THREAD

**Issue by kopeboy** [pubky/pkarr#91]
Just curious... Thanks.

**Comment by Nuhvi** [comment]
Mainline orders of magnitudes bigger DHT, twice as old and battle tested, and orders of magnitude simpler too https://github.com/pubky/pkarr/issues/5#issuecomment-1701608315

**Comment by kopeboy** [comment]
Nice, thank you for linking that long reply. So I guess the issue becomes: Make it clear that your implementation is nothing new but just good old, battle-tested, more efficient than IPFS, Mainline DHT BitTorrent.

Also, I guess some things have changed in the last 1.4 years?

**Comment by weex** [comment]
Seems like this is signed DNS over DHT.

**Comment by Nuhvi** [comment]
> Also, I guess some things have changed in the last 1.4 years?
Barely, the old JS implementation on npm that is used in app.pkarr.org to this day, is still perfectly compatible with the current rust version, both clients and relays etc.

I am trying to add enhancements here and there, but if you have been using Pkarr for 1.4 years, you wouldn't feel any breaking changes, because there haven't been any at protocol level.

> good old, battle-tested, more efficient than IPFS, Mainline DHT BitTorrent.
And more censorship resistant ... but also, it is better not just slightly, it is orders of magnitudes better on every one of these metrics, it is absurd.
